---
- hosts: digitalocean

  tasks:

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=DO2

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=DO2
      ssh_pub_key={{ lookup('file', '~/DO2.pub') }}
      api_token={{ do_token }}
    register: DO2

  - name: ensure droplet one exists
    digital_ocean: >
      state=absent
      command=droplet
      name=droplet-one
      unique_name=yes
      size_id=512mb
      region_id=nyc1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ DO2.ssh_key.id }}
      api_token={{ do_token }}
    register: droplet_one

