---
- hosts: drop
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
   - name: Install Squid
     apt: pkg=squid state=installed update_cache=true
     notify:
      - Start Squid
   - name: Change squid ACLS
     script: run-local-droplet 

  handlers:
   - name: Start Squid
     service: name=squid state=started



